// frontend/src/features/projects/ProjectsView.tsx
/**
 * ProjectsView —— 项目管理页：列表 / 新建 modal / 删除。
 * 重构：数据源换 projectStore；点击项目直接进入三栏 chat 工作区。
 */
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Plus, Trash2 } from 'lucide-react';
import { useProjectStore } from '@/stores/projectStore';

export default function ProjectsView() {
  const navigate = useNavigate();
  const { t } = useTranslation();
  const projects = useProjectStore((s) => s.projects);
  const fetchProjects = useProjectStore((s) => s.fetchProjects);
  const createProject = useProjectStore((s) => s.createProject);
  const deleteProject = useProjectStore((s) => s.deleteProject);
  const [showNew, setShowNew] = useState(false);
  const [newQuestion, setNewQuestion] = useState('');

  useEffect(() => {
    void fetchProjects();
  }, [fetchProjects]);

  const handleCreate = async () => {
    if (!newQuestion.trim()) return;
    const result = await createProject(newQuestion);
    setNewQuestion('');
    setShowNew(false);
    if (result?.id) navigate(`/research/${result.id}`);
  };

  const statusColor: Record<string, string> = {
    ACTIVE: 'bg-accent',
    COMPLETED: 'bg-success',
    ERROR: 'bg-danger',
  };

  return (
    <div className="flex-1 flex flex-col overflow-hidden min-w-0">
      <div className="px-6 py-4 border-b border-border-base/50 bg-bg-layer1 flex items-center justify-between">
        <h1 className="text-lg font-semibold text-text-strong">{t('nav.projects')}</h1>
        <button
          onClick={() => setShowNew(true)}
          className="flex items-center gap-2 px-3 py-1.5 rounded-md bg-accent text-white text-[13px] font-medium cursor-pointer hover:bg-accentHover transition-colors"
        >
          <Plus size={14} />
          <span>{t('common.new')}</span>
        </button>
      </div>

      <div className="flex-1 overflow-y-auto scrollbar-thin px-6 py-4">
        {projects.length === 0 ? (
          <div className="text-center py-16 text-text-faint text-sm">{t('common.noProjects')}</div>
        ) : (
          <div className="space-y-2">
            {projects.map((p) => (
              <div key={p.id} className="flex items-center gap-3 bg-bg-layer1 border border-border-base/50 rounded-lg px-4 py-3 hover:border-border-strong/50 transition-colors">
                <span className={`w-[6px] h-[6px] rounded-full flex-shrink-0 ${statusColor[p.status] || 'bg-text-muted'}`} />
                <button onClick={() => navigate(`/research/${p.id}`)} className="flex-1 text-left cursor-pointer">
                  <div className="text-[13px] font-medium text-text-strong truncate">{p.name}</div>
                  <div className="text-[11px] text-text-muted">{new Date(p.createdAt).toLocaleDateString()}</div>
                </button>
                <button
                  onClick={() => deleteProject(p.id)}
                  className="text-text-muted hover:text-danger transition-colors cursor-pointer p-1"
                >
                  <Trash2 size={14} />
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* New project modal */}
      {showNew && (
        <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={() => setShowNew(false)}>
          <div className="bg-bg-layer2 border border-border-strong rounded-xl p-6 w-[440px] max-w-[90vw]" onClick={(e) => e.stopPropagation()}>
            <h2 className="text-base font-semibold text-text-strong mb-4">{t('common.new')}</h2>
            <input
              value={newQuestion}
              onChange={(e) => setNewQuestion(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleCreate()}
              placeholder={t('common.enterQuestion') as string}
              autoFocus
              className="w-full px-3 py-2 bg-bg-base border border-border-base/50 rounded-lg text-[13px] text-text-strong outline-none placeholder:text-text-faint mb-4"
            />
            <div className="flex justify-end gap-2">
              <button onClick={() => setShowNew(false)} className="px-3 py-1.5 rounded-md text-[13px] text-text-base hover:bg-bg-layer3 cursor-pointer transition-colors">
                {t('common.cancel')}
              </button>
              <button
                onClick={handleCreate}
                disabled={!newQuestion.trim()}
                className="px-3 py-1.5 rounded-md bg-accent text-white text-[13px] font-medium disabled:opacity-30 disabled:cursor-not-allowed cursor-pointer"
              >
                Create
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// frontend-vue-backup/src/views/ProjectsView.vue
<template>
  <div class="projects-view">
    <div class="projects-header">
      <h2>{{ t('nav.projects') }}</h2>
      <el-button type="primary" @click="showNewDialog = true">{{
        t('common.new')
      }}</el-button>
    </div>

    <el-dialog
      v-model="showNewDialog"
      :title="t('common.new')"
      width="400px"
    >
      <el-input
        v-model="newQuestion"
        :placeholder="t('common.enterQuestion')"
        @keyup.enter="handleCreate"
      />
      <template #footer>
        <el-button @click="showNewDialog = false">取消</el-button>
        <el-button type="primary" @click="handleCreate">{{ t('common.new') }}</el-button>
      </template>
    </el-dialog>

    <div v-if="loading" class="loading">
      {{ t('common.loading') }}...
    </div>

    <div v-else class="projects-grid">
      <el-card
        v-for="project in projects"
        :key="project.id"
        class="project-card"
        shadow="hover"
      >
        <div class="card-body" @click="$router.push(`/research/${project.id}`)">
          <div class="card-title">{{ project.name }}</div>
          <div class="card-status" :class="getStatusClass(project.status)">
            {{ getStatusLabel(project.status) }}
          </div>
          <div class="card-date">{{ formatDate(project.createdAt) }}</div>
        </div>
        <div class="card-actions">
          <el-button size="small" @click="$router.push(`/research/${project.id}`)">
            {{ t('nav.research') }}
          </el-button>
          <el-button
            size="small"
            type="danger"
            @click="onDelete(project.id)"
          >
            {{ t('common.delete') }}
          </el-button>
        </div>
      </el-card>
    </div>

    <div v-if="!loading && projects.length === 0" class="empty-state">
      <p>{{ t('common.noProjects') }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useProjects } from '../composables/useProjects';

const { t } = useI18n();
const { projects, loading, fetchProjects, createProject, deleteProject } = useProjects();
const showNewDialog = ref(false);
const newQuestion = ref('');

function getStatusClass(status: string): string {
  const map: Record<string, string> = {
    ACTIVE: 'running',
    COMPLETED: 'done',
    ERROR: 'error',
    PENDING: 'ready',
  };
  return map[status] || 'ready';
}

function getStatusLabel(status: string): string {
  const cls = getStatusClass(status);
  return t(`status.${cls}`);
}

function formatDate(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('zh-CN', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return dateStr;
  }
}

async function handleCreate() {
  if (!newQuestion.value.trim()) return;
  await createProject(newQuestion.value);
  newQuestion.value = '';
  showNewDialog.value = false;
}

async function onDelete(id: string) {
  await deleteProject(id);
}
</script>

<style scoped>
.projects-view {
  flex: 1;
  padding: 24px;
  overflow-y: auto;
}

.projects-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
}

.projects-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 16px;
}

.project-card {
  cursor: default;
}

.card-body {
  cursor: pointer;
  padding: 4px 0;
}

.card-title {
  font-weight: bold;
  font-size: 16px;
  margin-bottom: 8px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.card-status {
  font-size: 12px;
  padding: 2px 8px;
  border-radius: 4px;
  display: inline-block;
  margin-bottom: 8px;
}

.card-status.ready { background: #e1f3d8; color: #67c23a; }
.card-status.running { background: #fdf6ec; color: #e6a23c; }
.card-status.done { background: #ecf5ff; color: #409eff; }
.card-status.error { background: #fef0f0; color: #f56c6c; }

.card-date {
  font-size: 12px;
  color: #909399;
  margin-bottom: 12px;
}

.card-actions {
  display: flex;
  gap: 8px;
  border-top: 1px solid #f0f0f0;
  padding-top: 8px;
  margin-top: 8px;
}

.loading {
  text-align: center;
  padding: 40px;
  color: #909399;
}

.empty-state {
  text-align: center;
  padding: 80px 20px;
  color: #909399;
}
</style>
