// frontend/src/views/ResearchView.vue
<template>
  <div class="research-view">
    <div class="main-content">
      <div class="center-panel">
        <PhaseTimeline
          :phases="phases"
          @select-phase="onSelectPhase"
        />
        <AgentLog :messages="logMessages" />
      </div>
      <InputBar
        v-if="!isRunning"
        :question="inputQuestion"
        @update:question="inputQuestion = $event"
        @send="onStartResearch"
        @stop="onStopResearch"
      />
    </div>
    <DetailPanel
      :selected-phase="selectedPhase"
      :show-approval="showApproval"
      :show-versions="showVersions"
      :show-papers="showPapers"
      :papers="papers"
      :approval-phase="approvalPhase"
      :approval-run-id="approvalRunId"
      :project-id="projectId"
      @close="closeDetailPanel"
      @approve="onApprove"
      @modify="onModify"
      @reject="onReject"
      @show-papers="showPapers = true; showVersions = false"
      @show-versions="showVersions = true; showPapers = false"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch, onMounted } from 'vue';
import { useRoute } from 'vue-router';
import PhaseTimeline from '../components/PhaseTimeline.vue';
import AgentLog from '../components/AgentLog.vue';
import DetailPanel from '../components/DetailPanel.vue';
import InputBar from '../components/InputBar.vue';
import { useSSE, type SSEMessage } from '../composables/useSSE';
import { useResearchStatus } from '../composables/useResearchStatus';
import client from '../api/client';
import type { PhaseRun, Paper } from '../api/types';

const route = useRoute();
const projectId = computed(() => route.params.projectId as string);

const phases = ref<PhaseRun[]>([]);
const logMessages = ref<Array<{ type: string; label: string; content: string; data?: unknown }>>([]);
const selectedPhase = ref<PhaseRun | null>(null);
const showApproval = ref(false);
const showVersions = ref(false);
const showPapers = ref(false);
const papers = ref<Paper[]>([]);
const isRunning = ref(false);
const inputQuestion = ref('');
const approvalPhase = ref('');
const approvalRunId = ref('');

const { connected, connect, disconnect, setHandlers } = useSSE();
const { setStatus } = useResearchStatus();

watch(connected, (val) => {
  if (!val && isRunning.value) {
    logMessages.value.push({
      type: 'error',
      label: 'Connection',
      content: 'SSE connection lost. Attempting reconnect...',
    });
  }
});

function loadPhases() {
  if (!projectId.value) return;
  client.get(`/projects/${projectId.value}/phases`)
    .then(({ data }) => {
      const phaseOrder = [
        'literature_search', 'gap_analysis', 'hypothesis',
        'experiment_design', 'experiment_execution',
        'evidence_evaluation', 'conclusion', 'report',
      ];
      phases.value = (Array.isArray(data) ? data : []).sort((a: PhaseRun, b: PhaseRun) => {
        const ia = phaseOrder.indexOf(a.phaseName);
        const ib = phaseOrder.indexOf(b.phaseName);
        return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib);
      });
      const activePhase = phases.value.find((p) => p.status === 'WAITING_APPROVAL');
      if (activePhase) {
        selectPhase(activePhase);
        showApproval.value = true;
        showVersions.value = false;
        showPapers.value = false;
      }
    })
    .catch(() => { phases.value = []; });
}

function loadPapers() {
  if (!projectId.value) return;
  client.get(`/projects/${projectId.value}/papers`)
    .then(({ data }) => { papers.value = Array.isArray(data) ? data : []; })
    .catch(() => { papers.value = []; });
}

function selectPhase(phase: PhaseRun) {
  selectedPhase.value = phase;
  showVersions.value = false;
  showPapers.value = false;
  if (phase.status === 'WAITING_APPROVAL') {
    showApproval.value = true;
    approvalPhase.value = phase.phaseName;
    approvalRunId.value = phase.phaseRunId;
  } else {
    showApproval.value = false;
  }
}

function onSelectPhase(phase: PhaseRun) {
  selectPhase(phase);
}

function closeDetailPanel() {
  selectedPhase.value = null;
  showApproval.value = false;
  showVersions.value = false;
  showPapers.value = false;
}

function handleSSEMessage(msg: SSEMessage) {
  const data = msg.data as Record<string, unknown>;
  const evt = msg.event;

  if (evt === 'run:start') {
    setStatus('running');
    logMessages.value.push({
      type: 'phase:start',
      label: 'Research',
      content: `研究开始: ${String(data.question ?? 'Unknown')}`,
    });
  } else if (evt === 'phase:start') {
    logMessages.value.push({
      type: 'phase:start',
      label: `Phase: ${String(data.phaseName ?? 'Unknown')}`,
      content: `开始阶段: ${String(data.phaseName ?? 'Unknown')}`,
    });
    loadPhases();
  } else if (evt === 'phase:complete') {
    logMessages.value.push({
      type: 'phase:complete',
      label: `Phase: ${String(data.phaseName ?? 'Unknown')}`,
      content: `阶段完成: ${String(data.phaseName ?? 'Unknown')}`,
    });
    loadPhases();
    loadPapers();
  } else if (evt === 'phase:error') {
    logMessages.value.push({
      type: 'error',
      label: `Phase: ${String(data.phaseName ?? 'Unknown')}`,
      content: `阶段错误: ${String(data.phaseName ?? 'Unknown')} - ${String(data.error ?? 'Unknown error')}`,
    });
    loadPhases();
  } else if (evt === 'thinking' || evt === 'message') {
    logMessages.value.push({
      type: 'thinking',
      label: 'Agent',
      content: String(data.content ?? String(data)),
    });
  } else if (evt === 'tool:calling') {
    logMessages.value.push({
      type: 'tool:calling',
      label: `Tool: ${String(data.toolName ?? 'Unknown')}`,
      content: JSON.stringify(data.input ?? {}, null, 2),
      data,
    });
  } else if (evt === 'tool:result') {
    logMessages.value.push({
      type: 'tool:result',
      label: `Tool: ${String(data.toolName ?? 'Unknown')}`,
      content: String(data.output ?? 'No output'),
      data,
    });
  } else if (evt === 'self:review') {
    logMessages.value.push({
      type: 'self:review',
      label: 'Self-Review',
      content: String(data.issues ? `Issues: ${data.issues}` : 'Review complete'),
      data,
    });
  } else if (evt === 'phase:awaiting_approval') {
    logMessages.value.push({
      type: 'phase:start',
      label: 'Approval',
      content: `等待审批: ${String(data.phaseName ?? 'Unknown')}`,
    });
    loadPhases();
    approvalPhase.value = String(data.phaseName ?? '');
    approvalRunId.value = String(data.runId ?? '');
    showApproval.value = true;
  } else if (evt === 'phase:approved') {
    logMessages.value.push({
      type: 'phase:complete',
      label: 'Approval',
      content: `已批准: ${String(data.phaseName ?? 'Unknown')}`,
    });
    showApproval.value = false;
    loadPhases();
  } else if (evt === 'phase:modified') {
    logMessages.value.push({
      type: 'message',
      label: 'Approval',
      content: `已提交修改: ${String(data.phaseName ?? 'Unknown')}`,
    });
    showApproval.value = false;
    loadPhases();
  } else if (evt === 'phase:rejected') {
    logMessages.value.push({
      type: 'error',
      label: 'Approval',
      content: `已拒绝: ${String(data.phaseName ?? 'Unknown')}`,
    });
    showApproval.value = false;
    loadPhases();
  } else if (evt === 'run:complete') {
    setStatus('done');
    logMessages.value.push({
      type: 'phase:complete',
      label: 'Research',
      content: '研究完成!',
    });
    isRunning.value = false;
    disconnect();
    loadPhases();
    loadPapers();
  } else if (evt === 'run:error') {
    setStatus('error');
    logMessages.value.push({
      type: 'error',
      label: 'Research',
      content: `研究错误: ${String(data.error ?? 'Unknown error')}`,
    });
    isRunning.value = false;
    disconnect();
  } else if (evt === 'search:result' || evt === 'paper:found') {
    logMessages.value.push({
      type: 'message',
      label: 'Paper',
      content: String(data.sourceTitle ?? data.title ?? 'Paper found'),
      data,
    });
  } else {
    logMessages.value.push({
      type: 'message',
      label: evt,
      content: typeof data === 'string' ? data : JSON.stringify(data, null, 2).substring(0, 500),
    });
  }
}

function onStartResearch(question: string) {
  if (!question.trim()) return;
  isRunning.value = true;
  setStatus('running');
  logMessages.value = [];
  disconnect();

  setHandlers({
    onMessage: handleSSEMessage,
    onConnect: () => {
      logMessages.value.push({
        type: 'message',
        label: 'Connection',
        content: 'SSE connected',
      });
    },
    onDisconnect: () => {
      logMessages.value.push({
        type: 'error',
        label: 'Connection',
        content: 'SSE disconnected',
      });
    },
  });

  client.post('/research/stream', { question, mode: 'manual' })
    .then(() => {
      logMessages.value.push({
        type: 'message',
        label: 'Research',
        content: `POST /research/stream initiated with question: ${question}`,
      });
    })
    .catch((err) => {
      logMessages.value.push({
        type: 'error',
        label: 'Research',
        content: `Failed to start: ${String(err)}`,
      });
      isRunning.value = false;
    });

  const sseUrl = `/api/research/stream?q=${encodeURIComponent(question)}`;
  connect(sseUrl);
}

function onStopResearch() {
  isRunning.value = false;
  disconnect();
  logMessages.value.push({
    type: 'message',
    label: 'Research',
    content: 'Research stopped by user',
  });
}

function onApprove() {
  submitDecision('approve', '');
}

function onModify(feedback: string) {
  submitDecision('modify', feedback);
}

function onReject(reason: string) {
  submitDecision('reject', reason);
}

function submitDecision(decision: string, feedback: string) {
  if (!projectId.value || !approvalRunId.value) return;
  client.post(`/projects/${projectId.value}/phases/${approvalRunId.value}/decision`, {
    decision,
    feedback,
  })
    .then(() => {
      showApproval.value = false;
      loadPhases();
    })
    .catch((err) => {
      logMessages.value.push({
        type: 'error',
        label: 'Approval',
        content: `Decision failed: ${String(err)}`,
      });
    });
}

onMounted(() => {
  loadPhases();
  loadPapers();
});
</script>

<style scoped>
.research-view {
  display: flex;
  flex: 1;
  overflow: hidden;
}

.main-content {
  display: flex;
  flex-direction: column;
  flex: 1;
  overflow: hidden;
}

.center-panel {
  display: flex;
  flex: 1;
  overflow: hidden;
}
</style>

// frontend/src/views/ResearchView.tsx
import { useState, useCallback, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Send, Square, X } from 'lucide-react';
import PhaseBar from '@/components/layout/PhaseBar';
import ChatArea from '@/components/chat/ChatArea';
import PhaseDetailDrawer from '@/components/layout/PhaseDetailDrawer';
import { useStore } from '@/store/useStore';
import client from '@/api/client';
import type { ChatMessage } from '@/components/chat/types';
import type { PhaseRun } from '@/api/types';

const storageKey = (pid: string) => `pf_chat_${pid}`;

export default function ResearchView() {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const { t } = useTranslation();
  const { setStatus } = useStore();

  const loadSaved = (): ChatMessage[] => {
    if (!projectId) return [];
    try { return JSON.parse(localStorage.getItem(storageKey(projectId)) || '[]') as ChatMessage[]; }
    catch { return []; }
  };
  const saveToStorage = (msgs: ChatMessage[]) => {
    if (!projectId) return;
    try { localStorage.setItem(storageKey(projectId), JSON.stringify(msgs)); } catch {}
  };

  const [messages, setMessages] = useState<ChatMessage[]>(loadSaved);
  const [input, setInput] = useState('');
  const [isRunning, setIsRunning] = useState(false);
  const [phases, setPhases] = useState<PhaseRun[]>([]);
  const [currentRunId, setCurrentRunId] = useState<string | null>(null);
  const [selectedPhase, setSelectedPhase] = useState<PhaseRun | null>(null);
  const eventSourceRef = useRef<EventSource | null>(null);
  let msgId = 0;

  // Sync messages to localStorage whenever they change
  useEffect(() => { saveToStorage(messages); }, [messages, projectId]);

  // Update msgId when messages change so new messages don't get duplicate IDs
  useEffect(() => {
    const maxId = messages.reduce((max, m) => Math.max(max, m.id), -1);
    msgId = maxId + 1;
  }, [messages]);

  useEffect(() => {
    if (!projectId) return;
    loadPhases();
  }, [projectId]);

  const loadPhases = async () => {
    if (!projectId) return;
    try {
      const { data } = await client.get<PhaseRun[]>(`/projects/${projectId}/phases`);
      const runs = Array.isArray(data) ? data : [];
      setPhases(runs);
      // If no saved messages, rebuild from phases
      if (runs.length > 0 && messages.length === 0) {
        const phaseOrder = ['literature_search', 'gap_analysis', 'hypothesis', 'experiment_design', 'experiment_execution', 'evidence_evaluation', 'conclusion', 'report'];
        const statusMsgs: ChatMessage[] = [];
        for (const name of phaseOrder) {
          const phaseRuns = runs.filter((r) => r.phaseName === name);
          if (phaseRuns.length > 0) {
            const latest = phaseRuns.sort((a, b) => b.phaseVersion - a.phaseVersion)[0];
            const status = latest.status === 'COMPLETED' ? ' ✓' : latest.status === 'RUNNING' ? ' ...' : latest.status === 'ERROR' ? ' ✗' : '';
            statusMsgs.push({ id: msgId++, role: 'assistant', content: `${t(`phases.${name}`) as string}${status}` });
          }
        }
        if (statusMsgs.length > 0) setMessages(statusMsgs);
      }
    } catch {}
  };

  const handleSSE = useCallback((event: string, data: Record<string, unknown>) => {
    setMessages((prev) => {
      const next = [...prev];
      const phaseLabel = (name: string) => t(`phases.${name}`) as string;

      if (event === 'run:start') {
        const rid = String(data.runId ?? '');
        if (rid) setCurrentRunId(rid);
        next.push({ id: msgId++, role: 'assistant', content: 'Research started.' });
      } else if (event === 'phase:start') {
        loadPhases();
        const phase = String(data.phaseName ?? '');
        next.push({ id: msgId++, role: 'assistant', content: `${phaseLabel(phase)}...` });
      } else if (event === 'phase:progress') {
        const phase = String(data.phaseName ?? '');
        const last = [...next].reverse().find((m) => m.content === `${phaseLabel(phase)}...`);
        if (last) last.content = `${phaseLabel(phase)}: ${String(data.progress ?? 'in progress')}`;
      } else if (event === 'phase:complete') {
        loadPhases();
        const phase = String(data.phaseName ?? '');
        const last = [...next].reverse().find((m) => m.content?.startsWith(phaseLabel(phase)));
        if (last) last.content = `${phaseLabel(phase)} ✓`;
      } else if (event === 'phase:error') {
        loadPhases();
        const phase = String(data.phaseName ?? '');
        next.push({ id: msgId++, role: 'assistant', content: `${phaseLabel(phase)} ✗ ${String(data.error ?? '')}` });
      } else if (event === 'phase:approved') {
        const phase = String(data.phaseName ?? '');
        next.push({ id: msgId++, role: 'assistant', content: `${phaseLabel(phase)} approved ✓` });
      } else if (event === 'phase:rejected') {
        const phase = String(data.phaseName ?? '');
        next.push({ id: msgId++, role: 'assistant', content: `${phaseLabel(phase)} rejected ✗` });
      } else if (event === 'phase:modified') {
        const phase = String(data.phaseName ?? '');
        next.push({ id: msgId++, role: 'assistant', content: `${phaseLabel(phase)} modified` });
      } else if (event === 'phase:awaiting_approval') {
        next.push({ id: msgId++, role: 'assistant', needsApproval: true, approvalSummary: String(data.summary ?? ''), approvalRunId: String(data.runId ?? '') });
      } else if (event === 'thinking' || event === 'message') {
        const text = String(data.content ?? String(data));
        const last = next[next.length - 1];
        if (last?.isThinking) { last.thinkingText = text; }
        else { next.push({ id: msgId++, role: 'assistant', isThinking: true, thinkingText: text }); }
      } else if (event === 'tool:calling') {
        const last = next[next.length - 1];
        if (last?.isThinking) { last.thinkingText = `${String(data.toolName ?? 'tool')}...`; }
      } else if (event === 'tool:result') {
        // Silent — tool result is internal
      } else if (event === 'self:review') {
        const passed = (data as Record<string, unknown>).passed as boolean;
        next.push({ id: msgId++, role: 'assistant', content: `Self-review: ${passed ? 'passed ✓' : 'issues found !'}` });
      } else if (event === 'search:result' || event === 'paper:found') {
        const last = next[next.length - 1];
        if (last?.papers) {
          last.papers.push({ title: String(data.sourceTitle ?? data.title ?? ''), authors: String(data.authors ?? data.sourceAuthors ?? ''), year: String(data.year ?? data.sourceYear ?? '') });
        } else {
          next.push({ id: msgId++, role: 'assistant', papers: [{ title: String(data.sourceTitle ?? data.title ?? ''), authors: String(data.authors ?? data.sourceAuthors ?? ''), year: String(data.year ?? data.sourceYear ?? '') }] });
        }
      } else if (event === 'hypothesis:proposed') {
        next.push({ id: msgId++, role: 'assistant', hypothesis: String(data.statement ?? '') });
      } else if (event === 'run:complete') {
        setIsRunning(false);
        setStatus('done');
        loadPhases();
        eventSourceRef.current?.close();
        next.push({ id: msgId++, role: 'assistant', content: t('common.complete') as string });
      } else if (event === 'run:error') {
        setIsRunning(false);
        setStatus('error');
        loadPhases();
        eventSourceRef.current?.close();
        next.push({ id: msgId++, role: 'assistant', content: `Error: ${String(data.error ?? '')}` });
      }
      return next;
    });
  }, [t, setStatus]);

  const startResearch = (question: string) => {
    setMessages((prev) => [...prev, { id: msgId++, role: 'user', content: question }]);
    setInput('');
    setIsRunning(true);
    setStatus('running');
    setCurrentRunId(null);

    const es = new EventSource(`/api/research/stream?q=${encodeURIComponent(question)}`);
    eventSourceRef.current = es;
    es.onmessage = (e) => {
      try {
        const parsed = JSON.parse(e.data);
        handleSSE(parsed.type ?? parsed.event ?? e.type, parsed);
      } catch {
        handleSSE('message', { content: e.data });
      }
    };
    es.onerror = () => {
      es.close();
      eventSourceRef.current = null;
    };
  };

  const stopResearch = async () => {
    eventSourceRef.current?.close();
    eventSourceRef.current = null;
    if (currentRunId) {
      try { await client.post(`/api/research/${currentRunId}/stop`); } catch {}
    }
    setIsRunning(false);
    setStatus('error');
    setCurrentRunId(null);
    setMessages((prev) => [...prev, { id: msgId++, role: 'assistant', content: 'Research stopped.' }]);
  };

  const submitDecision = async (runId: string, decision: string, feedback: string = '') => {
    if (!projectId) return;
    try {
      await client.post(`/api/projects/${projectId}/phases/${runId}/decision`, { decision, feedback });
    } catch {}
  };

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      <div className="flex flex-1 overflow-hidden">
        <div className="flex-1 flex flex-col overflow-hidden">
          <PhaseBar phases={phases} onSelectPhase={setSelectedPhase} />
          <ChatArea messages={messages} onApprove={(rid) => submitDecision(rid, 'approve')} onModify={(rid, fb) => submitDecision(rid, 'modify', fb)} onReject={(rid, reason) => submitDecision(rid, 'reject', reason)} />
          <div className="px-6 pb-4 pt-2 bg-bg-base">
            {isRunning && (
              <div className="flex items-center justify-between px-1 mb-2">
                <span className="flex items-center gap-2 text-[12px] text-text-muted">
                  <span className="w-[6px] h-[6px] rounded-full bg-warning animate-pulse" />
                  {t('common.running')}
                </span>
                <button onClick={stopResearch} className="flex items-center gap-1 text-[12px] text-danger hover:text-text-strong cursor-pointer transition-colors">
                  <Square size={10} />
                  <span>Stop</span>
                </button>
              </div>
            )}
            <div className="flex items-center gap-2 bg-bg-layer1 border border-border-base/50 rounded-xl min-h-[48px] transition-colors focus-within:border-border-strong">
              <textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); if (input.trim() && !isRunning) startResearch(input); } }}
                placeholder={isRunning ? (t('common.waiting') as string) : (t('common.enterQuestion') as string)}
                disabled={isRunning}
                className="flex-1 px-4 py-2.5 bg-transparent text-[13px] text-text-strong outline-none placeholder:text-text-faint resize-none disabled:opacity-50 max-h-[150px] min-h-[36px]"
                rows={1}
              />
              {isRunning ? (
                <button onClick={stopResearch} className="w-[30px] h-[30px] rounded-md flex items-center justify-center bg-danger text-white mr-1 mb-1 cursor-pointer flex-shrink-0">
                  <Square size={10} />
                </button>
              ) : (
                <button onClick={() => input.trim() && startResearch(input)} disabled={!input.trim()} className="w-[30px] h-[30px] rounded-md flex items-center justify-center bg-accent text-white disabled:opacity-30 disabled:cursor-not-allowed mr-1 mb-1 cursor-pointer flex-shrink-0">
                  <Send size={14} />
                </button>
              )}
            </div>
          </div>
        </div>
        {selectedPhase && (
          <PhaseDetailDrawer phase={selectedPhase} projectId={projectId!} onClose={() => setSelectedPhase(null)} />
        )}
      </div>
    </div>
  );
}
